### ISSUE TITLE
nullpointerexception - windows 10

### ISSUE THREAD

**Issue by nullpointerexceptionkek** [nullpointerexceptionkek/CDiscordRP#25]
** system Information **
Client Version: 1.0.0
Operating system: Windows 10
Operating system Version: 10.0
Java Version: 15.0.1
Java Vendor: Oracle Corporation
Thread: JavaFX Application Thread
**

java.lang.NullPointerException: Cannot invoke "lee.aspect.dev.cdiscordrp.application.controller.CallBackController.updateCurrentDisplay(lee.aspect.dev.cdiscordrp.application.core.Updates)" because "lee.aspect.dev.cdiscordrp.application.controller.LoadingController.callBackController" is null
    at lee.aspect.dev.cdiscordrp.application.core.RunLoopManager.lambda$updateDisplay$0(RunLoopManager.java:257)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by nullpointerexceptionkek** [comment]
cannot be reproduced
